# Generated by Django 5.0.6 on 2024-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="descriptions",
            field=models.TextField(default=""),
        ),
    ]
